GET http://localhost:3001/web/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJpYXQiOjE3MjMzMTkzNDIsImV4cCI6MTcyMzMyMjk0Mn0.t_Eq297isqp5n12opD6kHusbcRiy01YRpYld8e-OSow