GET http://localhost:3001/web/api/supplier
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluaXN0cmF0b3IiLCJpYXQiOjE3MjMzNDIzNTQsImV4cCI6MTcyMzM0NTk1NH0.yUuWchTfcZUP-VpBaG-IKG4s758BpURU0Ch8PX3ReV8